config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # TODO: enforce SSL for UsersController in production
  resources :users, except: :index do
    member do
      post 'resend_confirmation_token'
      post 'resend_unlock_token'
      get 'roles_on'
      post 'lock_user'
      post 'superadmin_role'
      post 'documentation_admin_role'
    end
  end

  namespace :users do
    get 'search/autocomplete'
    post 'selfremove'
  end

  post 'bookmarklets/add_item'
  post 'bookmarklets/remove_item'
  get 'bookmarklets/add'
  get 'bookmarklets/confirm'

  post 'scheduled_tasks/expire_cache'
  post 'scheduled_tasks/update_feeds'

  resources :documentations

  resources :input_sources do
    collection do
      get :find
    end
  end
  resources :input_source

  resources :hub_feeds, except: :new do
    collection do
      get 'autocomplete'
    end
    member do
      get 'reschedule_immediately'
      get 'more_details'
      get 'import'
      post 'import' => 'hub_feeds#import_items'
      get 'controls'
    end

    resources :feed_retrievals

    resources :feed_items do
      member do
        get 'content'
        get 'about'
        get 'related'
        get 'controls'
        delete 'remove_item'
        get 'copy_move_to_hub'
        post 'copy_item'
        post 'move_item'
      end
    end
    resources :tags
    resources :tag_filters
  end

  get 'remix/:url_key' => 'republished_feeds#show', :as => 'remix'
  get 'remix/:url_key/items' => 'republished_feeds#items', :as => 'remix_items'

  get 'export_import' => 'export_import#index'
  get 'export_import/download' => 'export_import#download'
  post 'export_import' => 'export_import#import'

  resources :hubs do
    get 'tag/rss/:name' => 'tags#rss', :as => 'tag_rss', :constraints => { name: /.+/ }
    get 'tag/atom/:name' => 'tags#atom', :as => 'tag_atom', :constraints => { name: /.+/ }
    get 'tag/json/:name' => 'tags#json', :as => 'tag_json', :constraints => { name: /.+/ }
    get 'tag/xml/:name' => 'tags#xml', :as => 'tag_xml', :constraints => { name: /.+/ }
    get 'tag/:name/statistics' => 'tags#statistics', :as => 'tag_statistics', :constraints => { name: /.+/ }
    get 'tag/:name' => 'tags#show', :as => 'tag_show', :constraints => { name: /.+/ }, :defaults => { :format => 'html' }
    post 'tag/:name/description' => 'tags#description', :as => 'tag_description', :constraints => { name: /.+/ }

    get 'user/:username' => 'users#hub_items', :as => 'user_hub_items', :constraints => { username: /[^\/]+/ }
    get 'user/:username/tags' => 'tags#index', :as => 'user_hub_items_tags', :constraints => { username: /[^\/]+/ }
    get 'user/:username/filters' => 'tag_filters#index', :as => 'user_hub_items_filters', :constraints => { username: /[^\/]+/ }
    get 'user/:username/updates' => 'feed_retrievals#index', :as => 'user_hub_items_updates', :constraints => { username: /[^\/]+/ }
    get 'user/:username/about' => 'hub_feeds#show', :as => 'user_hub_items_about', :constraints => { username: /[^\/]+/ }

    get 'user/:username/rss' => 'users#tags_rss', :as => 'user_tags_rss', :constraints => { username: /[^\/]+/ }
    get 'user/:username/atom' => 'users#tags_atom', :as => 'user_tags_atom', :constraints => { username: /[^\/]+/ }
    get 'user/:username/json' => 'users#tags_json', :as => 'user_tags_json', :constraints => { username: /[^\/]+/ }
    get 'user/:username/xml' => 'users#tags_xml', :as => 'user_tags_xml', :constraints => { username: /[^\/]+/ }
    get 'user/:username/tag/:tagname(/:deprecated)' => 'users#tags', :as => 'user_tags_name', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/rss' => 'users#tags_rss', :as => 'user_tags_name_rss', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/atom' => 'users#tags_atom', :as => 'user_tags_name_atom', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/json' => 'users#tags_json', :as => 'user_tags_name_json', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/xml' => 'users#tags_xml', :as => 'user_tags_name_xml', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }

    get 'tags_used_not_approved' => 'tags#tags_used_not_approved'
    get 'deprecated_tags' => 'tags#deprecated_tags'
    get 'tags_approved' => 'tags#tags_approved'

    member do
      get 'about'
      post 'recalc_all_tags'
      get 'item_search'
      post 'removed_tag_suggestion'
      post 'add_feed'
      put 'unsubscribe_feed/:feed_id' => 'hubs#unsubscribe_feed', as: 'unsubscribe_feed'
      get 'custom_republished_feeds'
      get 'tag_controls'
      get 'items'
      get 'by_date/:year/:month/:day' => 'hubs#by_date', :as => 'by_date'
      get 'retrievals'
      get 'my_bookmark_collections'
      get 'taggers'
      get 'team'
      get 'statistics'
      get 'notifications'
      get 'settings'
      get 'scoreboard'
      post 'add_roles'
      post 'remove_roles'
      post 'request_rights'
      get 'contact'
      get 'created'
      post 'set_notifications'
      post 'set_user_notifications'
      post 'set_settings'
      get 'active_taggers'
      post 'approve_tag'
      post 'unapprove_tag'
      post 'deprecate_tag'
      post 'undeprecate_tag'
      delete 'remove_delimiter'
      post 'leave'
    end

    collection do
      get 'list'
      get 'meta'
      get 'my'
      get 'background_activity'
      get 'all_items'
      get 'search'
      delete 'destroy_hubs', as: 'destroy_hubs'
    end

    resources :hub_feeds do
      collection do
        get 'autocomplete'
      end
      member do
        get 'reschedule_immediately'
        get 'more_details'
        get 'controls'
      end
    end

    resources :republished_feeds do
      member do
        get 'items'
        get 'inputs'
        get 'removals'
        get 'more_details'
      end
    end

    resources :tags do
      collection do
        get 'autocomplete'
      end
    end

    resources :tag_filters

    resources :feed_items do
      resources :tag_filters

      member do
        get 'tag_list'
        get 'content'
        get 'related'
        get 'tags_actions'
      end
      #      collection do
      #        get 'by_date/:year/:month/:day' => 'feed_items#by_date', :as => 'by_date'
      #      end
    end

    resources :messages, only: %i[new create]
  end

  devise_for :users, path: 'accounts', controllers: {
    registrations: 'users/registrations'
  }

  # Allow users to log out using both DELETE and GET
  devise_scope :user do
    get '/accounts/sign_out', to: 'devise/sessions#destroy'
  end

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.has_role? :superadmin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    root 'home#index'

    resources :user_approvals, only: [:index] do
      get :approve
      get :deny
    end

    resources :users, only: :index
    resources :hubs, only: %i[index destroy]
    resources :settings, only: %i[new create update]
  end
  root 'hubs#home'
end

app/controllers/republished_feeds_controller.rb
# frozen_string_literal: true
class RepublishedFeedsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :items, :inputs, :removals]
  before_action :load_republished_feed, except: [:new, :create, :index]
  before_action :load_hub, only: [:new, :create, :index]
  before_action :register_breadcrumb

  after_action :verify_authorized, except: :index

  # Beef up cache rules.
  caches_action :index, :show, :items, :inputs, :removals, unless: proc { |_c| current_user }, expires_in: Tagteam::Application.config.default_action_cache_time, cache_path: proc {
    Digest::MD5.hexdigest(request.fullpath + '&per_page=' + get_per_page)
  }

  protect_from_forgery except: :items

  # A list of RepublishedFeeds (aka "remixed feeds") in a hub. Returns html, json, and xml.
  def index
    @republished_feeds = @hub.republished_feeds.paginate(page: params[:page], per_page: get_per_page)
    respond_to do |format|
      format.html { render layout: request.xhr? ? false : 'tabs' }
      format.json { render_for_api :default, json: @republished_feeds }
      format.xml { render_for_api :default, xml: @republished_feeds }
    end
  end

  # An individual RepublishedFeed. Returns html, json, and xml.
  def show
    @show_auto_discovery_params = remix_items_url(@republished_feed.url_key, format: :rss)
    respond_to do |format|
      format.html { render layout: request.xhr? ? false : 'tabs' }
      format.json { render_for_api :default, json: @republished_feed }
      format.xml { render_for_api :default, xml: @republished_feed }
    end
  end

  # A paginated list of FeedItems in this RepublishedFeed. Returns html, rss, atom, json, and xml.
  def items
    Feeds::StoreFeedVisitorJob.perform_later(
      request.path,
      request.format.symbol.to_s,
      request.remote_ip,
      request.user_agent
    )

    @show_auto_discovery_params = items_hub_republished_feed_url(@hub, @republished_feed, format: :rss)
    @search = @republished_feed.item_search
    unless @search.blank?
      @search.build do
        paginate page: params[:page], per_page: get_per_page
      end
      @search.execute!
    end
    respond_to do |format|
      format.html do
        template = params[:view] == 'grid' ? 'items_grid' : 'items'
        render template, layout: request.xhr? ? false : 'tabs'
      end
      format.rss {}
      format.atom {}
      format.json { render_for_api :default, json: @search.blank? ? [] : @search.results }
      format.xml { render_for_api :default, xml: @search.blank? ? [] : @search.results }
    end
  end

  # List the InputSource objects that add items to this RepublishedFeed.
  def inputs
    render layout: request.xhr? ? false : 'tabs'
  end

  # List the InputSource objects that remove items from this RepublishedFeed.
  def removals
    render layout: request.xhr? ? false : 'tabs'
  end

  def new
    @republished_feed = RepublishedFeed.new(hub_id: @hub.id)
    authorize @republished_feed
  end

  def create
    @republished_feed = RepublishedFeed.create_with_user(current_user, @hub, params)

    if @republished_feed.errors.present?
      skip_authorization
    else
      authorize @republished_feed
    end

    respond_to do |format|
      if @republished_feed.errors.present?
        # new instance needed to avoid breaking form
        flash[:error] = 'Could not add that remix.'
        format.html { render action: :new }
      else
        flash[:notice] = 'Created a new remix. You should switch to the "inputs" tab and add items for publishing.'
        format.html { redirect_to action: :show, id: @republished_feed.id }
      end
    end
  end

  def update
    @republished_feed.attributes = params[:republished_feed]
    respond_to do |format|
      if @republished_feed.save
        current_user.has_role!(:editor, @republished_feed)
        flash[:notice] = 'Edited that remix.'
        format.html { redirect_to action: :show, id: @republished_feed.id }
      else
        flash[:error] = 'Could not edit that remix.'
        format.html { render action: :update }
      end
    end
  end

  def edit; end

  def destroy
    @republished_feed.destroy
    flash[:notice] = 'Removed that remix.'
    redirect_to(hub_path(@hub))
  rescue
    flash[:error] = "Couldn't remove that remix."
    redirect_to(hub_path(@hub))
  end

  private

  def load_hub
    hub_id = params[:republished_feed].blank? ? params[:hub_id] : params[:republished_feed][:hub_id]
    @hub = Hub.find(hub_id)
  end

  def load_republished_feed
    @republished_feed = if params[:url_key].blank?
                          RepublishedFeed.find(params[:id])
                        else
                          RepublishedFeed.find_by!(url_key: params[:url_key])
                        end
    authorize @republished_feed

    @hub = @republished_feed.hub
  end

  def register_breadcrumb
    breadcrumbs.add @hub.title, hub_path(@hub)
  end
end

app/views/republished_feeds/_list_item.html.haml
- hub = @hub.blank? ? republished_feed.hub : @hub
%li.republished_feed.hover_row{ id: "republished_feed_#{republished_feed.id}" }
  .media
    - if current_user && (current_user.is?(:owner, hub) || current_user.is?(:owner, republished_feed) || current_user.superadmin?)
      .pull-right
        = link_to edit_hub_republished_feed_path(hub, republished_feed), title: 'Edit this item' do
          = fa_icon 'pencil'
        = link_to hub_republished_feed_path(hub, republished_feed),
          method: :delete, confirm: 'Are you sure?', title: 'Delete this item' do
          = fa_icon 'times'
    .media-left
      = link_to '#',
        class: 'republished_feed_more_control',
        data_republished_feed_id: republished_feed.id do
        = fa_icon 'caret-right'
    .media-body
      %h2= hub.title
      = link_to(republished_feed.title, remix_path(republished_feed.url_key))
      |
      = link_to('RSS', remix_items_path(republished_feed.url_key, format: :rss))
      \(#{pluralize(FeedSubscriber.count_for(remix_items_path(republished_feed.url_key, format: :rss)), 'subscriber')})
      = link_to('ATOM', remix_items_path(republished_feed.url_key, format: :atom))
      \(#{pluralize(FeedSubscriber.count_for(remix_items_path(republished_feed.url_key, format: :atom)), 'subscriber')})
      = link_to('JSON', remix_items_path(republished_feed.url_key, format: :json, callback: 'callback'))
      \(#{pluralize(FeedSubscriber.count_for(remix_items_path(republished_feed.url_key, format: :json)), 'subscriber')})
      = render 'more_details', republished_feed: republished_feed

app/views/republished_feeds/_more_details.html.haml
.metadata.hidden
  = pluralize republished_feed.inputs.length, 'input'
  ,
  \#{pluralize republished_feed.removals.length, 'removal'}

app/views/republished_feeds/_tabs.html.haml
%li{:class => "#{'active' if active == 'items'}"}
  = documentation('republished-feed-items-tab')
  = link_to('Items', remix_items_path(@republished_feed.url_key))
  .nav-pill-arrow
%li{:class => "#{'active' if active == 'about'}"}
  = documentation('republished-feed-about-tab')
  = link_to('About', remix_path(@republished_feed.url_key))
  .nav-pill-arrow
%li{:class => "#{'active' if active == 'inputs'}"}
  = documentation('republished-feed-inputs-tab')
  = link_to('Inputs', inputs_hub_republished_feed_path(@hub, @republished_feed))
  .nav-pill-arrow
%li{:class => "#{'active' if active == 'removals'}"}
  = documentation('republished-feed-removals-tab')
  = link_to('Removals', removals_hub_republished_feed_path(@hub, @republished_feed))
  .nav-pill-arrow

app/views/republished_feeds/_top_panel.html.haml
.col-sm-8
  %h1
    Remix: #{republished_feed}
    %span.actions
      - if current_user && (current_user.is?(:owner, republished_feed) || current_user.is?(:superadmin))
        = link_to edit_hub_republished_feed_path(hub, republished_feed), title: 'Edit this remix' do
          = fa_icon 'pencil'
        = link_to hub_republished_feed_path(hub, republished_feed), method: :delete, confirm: 'Are you sure you want to delete this remix?', title: 'Delete this remix' do
          = fa_icon 'remove'

.col-sm-4
  .export-menu.text-right
    = link_to remix_items_path(republished_feed.url_key, format: :rss), title: 'An RSS feed of all items in this remix, with tag filters applied.', class: 'btn btn-default' do
      = image_tag('protocol_rss.png', width: 12, height: 12)
      RSS
      %span.badge
        = FeedSubscriber.count_for(remix_items_path(republished_feed.url_key, format: :rss))
    = link_to remix_items_path(republished_feed.url_key, format: :atom), title: 'An Atom feed of all items in this remix, with tag filters applied.', class: 'btn btn-default' do
      = image_tag('protocol_atom.png', width: 12, height: 12)
      ATOM
      %span.badge
        = FeedSubscriber.count_for(remix_items_path(republished_feed.url_key, format: :atom))
    = link_to remix_items_path(republished_feed.url_key, format: :json, callback: 'callback'), title: 'jsonp of all items in this remix, with tag filters applied.', class: 'btn btn-default' do
      = image_tag('protocol_json.png', width: 12, height: 12)
      JSON
      %span.badge
        = FeedSubscriber.count_for(remix_items_path(republished_feed.url_key, format: :json))

app/views/republished_feeds/edit.html.haml
%h1 Edit this remix feed
= render :partial => 'shared/forms/republished_feed'

app/views/republished_feeds/index.html.haml
- content_for :top_panel do
  = render partial: 'hubs/top_panel', locals: { hub: @hub }
- content_for :tabs do
  = render partial: 'hubs/tabs', locals: { active: 'remixes' }
- content_for :tab_content do
  .republished_feeds.nicely-padded
    %h1
      - if current_user && (current_user.is?(%i[owner remixer], @hub) || current_user.superadmin?)
        .pull-right
          = link_to new_hub_republished_feed_path(@hub), class: 'new_object btn btn-success' do
            = fa_icon 'plus-circle', text: 'New remix feed'
      Remix feeds
    - if @republished_feeds.empty?
      %p This hub currently has no republished feeds.
    %div{ id: "republished_feed_list_#{@hub.id}" }
      .text-right
        = render partial: 'shared/paginate', object: @republished_feeds, as: :results
      %ul.republished_feeds.list-unstyled.nicely-padded
        = render partial: 'republished_feeds/list_item',
          collection: @republished_feeds,
          as: :republished_feed
      .text-center
        = render partial: 'shared/paginate', object: @republished_feeds, as: :results

app/views/republished_feeds/inputs.html.haml
- content_for :top_panel do
  = render partial: 'top_panel', locals: { hub: @hub, republished_feed: @republished_feed }
- content_for :tabs do
  = render partial: 'tabs', locals: { active: 'inputs' }
- content_for :tab_content do
  .nicely-padded
    %h3 Inputs
    %p These feeds, tags, searches, and items serve are used to create this remix:
    - if !@republished_feed.input_sources.any? {|ins| ins.effect == 'add'}
      %i No items to display.
    - else
      %ul.list-unstyled
        = render partial: 'input_sources/list_item',
          collection: @republished_feed.input_sources.reject{|ins| ins.effect != 'add'},
          as: :input_source

app/views/republished_feeds/items.html.haml
- content_for :top_panel do
  = render partial: 'top_panel', locals: { hub: @hub, republished_feed: @republished_feed }
- content_for :tabs do
  = render partial: 'tabs', locals: { active: 'items' }
- content_for :tab_content do
  - if @search.blank? || @search.total == 0
    .nicely-padded
      %p
        None yet. Please add items or tags from #{link_to "the hub", items_hub_path(@hub)}.
  - else
    = render partial: 'feed_items/alter_view', locals: { view: 'list', results: @search.results }
    %ul.list-unstyled.flush-top
      = render partial: 'feed_items/list_item', collection: @search.results, as: :feed_item
    .text-center
      = render partial: 'shared/paginate', object: @search.results, as: :results

app/views/republished_feeds/items_grid.html.haml
- content_for :top_panel do
  = render partial: 'top_panel', locals: { hub: @hub, republished_feed: @republished_feed }
- content_for :tabs do
  = render partial: 'tabs', locals: { active: 'items' }
- content_for :tab_content do
  - if @search.blank? || @search.total == 0
    %p
      None yet. Please add items or tags from #{link_to "the hub", items_hub_path(@hub)}.
  - else
    = render partial: 'feed_items/alter_view', locals: { view: 'grid', results: @search.results }
    = render partial: 'feed_items/grid', object: @search.results, as: :feed_items

app/views/republished_feeds/new.html.haml
%h1 Create a new remix feed
= render :partial => 'shared/forms/republished_feed'

app/views/republished_feeds/removals.html.haml
- content_for :top_panel do
  = render partial: 'top_panel', locals: { hub: @hub, republished_feed: @republished_feed }
- content_for :tabs do
  = render partial: 'tabs', locals: { active: 'removals' }
- content_for :tab_content do
  .nicely-padded
    %h3 Removals
    %p These feeds, tags, searches and items are removed from this remix before publishing:
    - if !@republished_feed.input_sources.any? {|ins| ins.effect == 'remove'}
      %i No items to display.
    - else
      %ul.list-unstyled
        = render partial: 'input_sources/list_item',
          collection: @republished_feed.input_sources.reject{|ins| ins.effect != 'remove'},
          as: :input_source

app/views/republished_feeds/show.html.haml
- content_for :top_panel do
  = render partial: 'top_panel', locals: { hub: @hub, republished_feed: @republished_feed }
- content_for :tabs do
  = render partial: 'tabs', locals: { active: 'about' }
- content_for :tab_content do
  .nicely-padded
    %h3 Description:
    - unless @republished_feed.description.blank?
      = sanitize @republished_feed.description
    %h3 Owners:
    = @republished_feed.owners.collect{|o| o.username}.join(', ')