config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # TODO: enforce SSL for UsersController in production
  resources :users, except: :index do
    member do
      post 'resend_confirmation_token'
      post 'resend_unlock_token'
      get 'roles_on'
      post 'lock_user'
      post 'superadmin_role'
      post 'documentation_admin_role'
    end
  end

  namespace :users do
    get 'search/autocomplete'
    post 'selfremove'
  end

  post 'bookmarklets/add_item'
  post 'bookmarklets/remove_item'
  get 'bookmarklets/add'
  get 'bookmarklets/confirm'

  post 'scheduled_tasks/expire_cache'
  post 'scheduled_tasks/update_feeds'

  resources :documentations

  resources :input_sources do
    collection do
      get :find
    end
  end
  resources :input_source

  resources :hub_feeds, except: :new do
    collection do
      get 'autocomplete'
    end
    member do
      get 'reschedule_immediately'
      get 'more_details'
      get 'import'
      post 'import' => 'hub_feeds#import_items'
      get 'controls'
    end

    resources :feed_retrievals

    resources :feed_items do
      member do
        get 'content'
        get 'about'
        get 'related'
        get 'controls'
        delete 'remove_item'
        get 'copy_move_to_hub'
        post 'copy_item'
        post 'move_item'
      end
    end
    resources :tags
    resources :tag_filters
  end

  get 'remix/:url_key' => 'republished_feeds#show', :as => 'remix'
  get 'remix/:url_key/items' => 'republished_feeds#items', :as => 'remix_items'

  get 'export_import' => 'export_import#index'
  get 'export_import/download' => 'export_import#download'
  post 'export_import' => 'export_import#import'

  resources :hubs do
    get 'tag/rss/:name' => 'tags#rss', :as => 'tag_rss', :constraints => { name: /.+/ }
    get 'tag/atom/:name' => 'tags#atom', :as => 'tag_atom', :constraints => { name: /.+/ }
    get 'tag/json/:name' => 'tags#json', :as => 'tag_json', :constraints => { name: /.+/ }
    get 'tag/xml/:name' => 'tags#xml', :as => 'tag_xml', :constraints => { name: /.+/ }
    get 'tag/:name/statistics' => 'tags#statistics', :as => 'tag_statistics', :constraints => { name: /.+/ }
    get 'tag/:name' => 'tags#show', :as => 'tag_show', :constraints => { name: /.+/ }, :defaults => { :format => 'html' }
    post 'tag/:name/description' => 'tags#description', :as => 'tag_description', :constraints => { name: /.+/ }

    get 'user/:username' => 'users#hub_items', :as => 'user_hub_items', :constraints => { username: /[^\/]+/ }
    get 'user/:username/tags' => 'tags#index', :as => 'user_hub_items_tags', :constraints => { username: /[^\/]+/ }
    get 'user/:username/filters' => 'tag_filters#index', :as => 'user_hub_items_filters', :constraints => { username: /[^\/]+/ }
    get 'user/:username/updates' => 'feed_retrievals#index', :as => 'user_hub_items_updates', :constraints => { username: /[^\/]+/ }
    get 'user/:username/about' => 'hub_feeds#show', :as => 'user_hub_items_about', :constraints => { username: /[^\/]+/ }

    get 'user/:username/rss' => 'users#tags_rss', :as => 'user_tags_rss', :constraints => { username: /[^\/]+/ }
    get 'user/:username/atom' => 'users#tags_atom', :as => 'user_tags_atom', :constraints => { username: /[^\/]+/ }
    get 'user/:username/json' => 'users#tags_json', :as => 'user_tags_json', :constraints => { username: /[^\/]+/ }
    get 'user/:username/xml' => 'users#tags_xml', :as => 'user_tags_xml', :constraints => { username: /[^\/]+/ }
    get 'user/:username/tag/:tagname(/:deprecated)' => 'users#tags', :as => 'user_tags_name', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/rss' => 'users#tags_rss', :as => 'user_tags_name_rss', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/atom' => 'users#tags_atom', :as => 'user_tags_name_atom', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/json' => 'users#tags_json', :as => 'user_tags_name_json', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/xml' => 'users#tags_xml', :as => 'user_tags_name_xml', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }

    get 'tags_used_not_approved' => 'tags#tags_used_not_approved'
    get 'deprecated_tags' => 'tags#deprecated_tags'
    get 'tags_approved' => 'tags#tags_approved'

    member do
      get 'about'
      post 'recalc_all_tags'
      get 'item_search'
      post 'removed_tag_suggestion'
      post 'add_feed'
      put 'unsubscribe_feed/:feed_id' => 'hubs#unsubscribe_feed', as: 'unsubscribe_feed'
      get 'custom_republished_feeds'
      get 'tag_controls'
      get 'items'
      get 'by_date/:year/:month/:day' => 'hubs#by_date', :as => 'by_date'
      get 'retrievals'
      get 'my_bookmark_collections'
      get 'taggers'
      get 'team'
      get 'statistics'
      get 'notifications'
      get 'settings'
      get 'scoreboard'
      post 'add_roles'
      post 'remove_roles'
      post 'request_rights'
      get 'contact'
      get 'created'
      post 'set_notifications'
      post 'set_user_notifications'
      post 'set_settings'
      get 'active_taggers'
      post 'approve_tag'
      post 'unapprove_tag'
      post 'deprecate_tag'
      post 'undeprecate_tag'
      delete 'remove_delimiter'
      post 'leave'
    end

    collection do
      get 'list'
      get 'meta'
      get 'my'
      get 'background_activity'
      get 'all_items'
      get 'search'
      delete 'destroy_hubs', as: 'destroy_hubs'
    end

    resources :hub_feeds do
      collection do
        get 'autocomplete'
      end
      member do
        get 'reschedule_immediately'
        get 'more_details'
        get 'controls'
      end
    end

    resources :republished_feeds do
      member do
        get 'items'
        get 'inputs'
        get 'removals'
        get 'more_details'
      end
    end

    resources :tags do
      collection do
        get 'autocomplete'
      end
    end

    resources :tag_filters

    resources :feed_items do
      resources :tag_filters

      member do
        get 'tag_list'
        get 'content'
        get 'related'
        get 'tags_actions'
      end
      #      collection do
      #        get 'by_date/:year/:month/:day' => 'feed_items#by_date', :as => 'by_date'
      #      end
    end

    resources :messages, only: %i[new create]
  end

  devise_for :users, path: 'accounts', controllers: {
    registrations: 'users/registrations'
  }

  # Allow users to log out using both DELETE and GET
  devise_scope :user do
    get '/accounts/sign_out', to: 'devise/sessions#destroy'
  end

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.has_role? :superadmin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    root 'home#index'

    resources :user_approvals, only: [:index] do
      get :approve
      get :deny
    end

    resources :users, only: :index
    resources :hubs, only: %i[index destroy]
    resources :settings, only: %i[new create update]
  end
  root 'hubs#home'
end

app/views/shared/_bookmarklet_button.html.haml
%a.btn.btn-success{ href: "javascript:(function(){f='#{bookmarklets_add_url}?feed_item%5burl%5d='+encodeURIComponent(window.location.href)+'&feed_item%5btitle%5d='+encodeURIComponent(document.title)+'&feed_item%5bdescription%5d='+encodeURIComponent(''+(window.getSelection?window.getSelection():document.getSelection?document.getSelection():document.selection.createRange().text))+'&';a=function(){if(!window.open(f+'noui=1&jump=doclose','tagteam','links=0,scrollbars=1,toolbar=0,width=710,height=900'))location.href=f+'jump=yes'};if(/Firefox/.test(navigator.userAgent)){setTimeout(a,0)}else{a()}})()" }
  = fa_icon 'plus-circle', text: 'Add to TagTeam'

app/views/shared/_flashes.html.haml
- if flash.present?
  - if flash[:notice].present?
    .alert.alert-success.alert-dismissable.col-md-12{ role: 'alert' }
      %button.close{ 'data-dismiss': 'alert', type: 'button' }
        %span{ 'aria-hidden': 'true' } ×
        %span.sr-only Close
      %strong= flash[:notice]
  - if flash[:error].present?
    .alert.alert-danger.alert-dismissable.col-md-12{ role: 'alert' }
      %button.close{ 'data-dismiss': 'alert', type: 'button' }
        %span{ 'aria-hidden': 'true' } ×
        %span.sr-only Close
      %strong= flash[:error]
  - if flash[:alert].present?
    .alert.alert-warning.alert-dismissable.col-md-12{ role: 'alert' }
      %button.close{ 'data-dismiss': 'alert', type: 'button' }
        %span{ 'aria-hidden': 'true' } ×
        %span.sr-only Close
      %strong= flash[:alert]

app/views/shared/_footer.html.haml
%footer.footer.container
  .col-md-12
    - if show_liblab?
      = image_tag 'LL_mini.png', alt: 'Library Lab Logo', class: 'll-logo'
      %p
        Thanks to the generous support of the
        = succeed "," do
          %a{:href => "http://lab.library.harvard.edu/"} Harvard Library Lab
        = succeed "," do
          %a{:href => "https://osc.hul.harvard.edu"} Harvard Library Office for Scholarly Communication
        = succeed "," do
          %a{:href => "http://cyber.law.harvard.edu"} Berkman Klein Center for Internet &amp; Society
        %a{:href => "http://www.arcadiafund.org.uk"} Arcadia Fund
        and the
        = succeed "." do
          %a{:href => "http://www.arnoldfoundation.org/"} Laura and John Arnold Foundation

app/views/shared/_logo.html.haml
.jumbotron.text-center
  %h1.title= fa_icon 'bolt', text: 'TagTeam'
  %p The open-source tagging platform and feed aggregator.
  = link_to "Start a hub", new_hub_path, class: 'btn btn-primary btn-lg start-hub'

app/views/shared/_paginate.html.haml
- show_per_page_select = true if local_assigns[:show_per_page_select].blank?
= will_paginate results,
  renderer: BootstrapPagination::Rails,
  inner_window: 1,
  outer_window: 0,
  next_label: fa_icon('chevron-right'),
  previous_label: fa_icon('chevron-left'),
  param_name: local_assigns[:param_name] || 'page',
  params: { anchor: local_assigns[:anchor] || nil }
- if results.total_pages > 1
  %span.pagination-counts= page_entries_info results
  - if show_per_page_select.present?
    %span.pagination-per-page
      = select_tag :per_page, options_for_select([25, 50, 100], params[:per_page].to_i || et_per_page),
        onchange: "if(this.value){ window.location='?per_page='+this.value; }"