config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # TODO: enforce SSL for UsersController in production
  resources :users, except: :index do
    member do
      post 'resend_confirmation_token'
      post 'resend_unlock_token'
      get 'roles_on'
      post 'lock_user'
      post 'superadmin_role'
      post 'documentation_admin_role'
    end
  end

  namespace :users do
    get 'search/autocomplete'
    post 'selfremove'
  end

  post 'bookmarklets/add_item'
  post 'bookmarklets/remove_item'
  get 'bookmarklets/add'
  get 'bookmarklets/confirm'

  post 'scheduled_tasks/expire_cache'
  post 'scheduled_tasks/update_feeds'

  resources :documentations

  resources :input_sources do
    collection do
      get :find
    end
  end
  resources :input_source

  resources :hub_feeds, except: :new do
    collection do
      get 'autocomplete'
    end
    member do
      get 'reschedule_immediately'
      get 'more_details'
      get 'import'
      post 'import' => 'hub_feeds#import_items'
      get 'controls'
    end

    resources :feed_retrievals

    resources :feed_items do
      member do
        get 'content'
        get 'about'
        get 'related'
        get 'controls'
        delete 'remove_item'
        get 'copy_move_to_hub'
        post 'copy_item'
        post 'move_item'
      end
    end
    resources :tags
    resources :tag_filters
  end

  get 'remix/:url_key' => 'republished_feeds#show', :as => 'remix'
  get 'remix/:url_key/items' => 'republished_feeds#items', :as => 'remix_items'

  get 'export_import' => 'export_import#index'
  get 'export_import/download' => 'export_import#download'
  post 'export_import' => 'export_import#import'

  resources :hubs do
    get 'tag/rss/:name' => 'tags#rss', :as => 'tag_rss', :constraints => { name: /.+/ }
    get 'tag/atom/:name' => 'tags#atom', :as => 'tag_atom', :constraints => { name: /.+/ }
    get 'tag/json/:name' => 'tags#json', :as => 'tag_json', :constraints => { name: /.+/ }
    get 'tag/xml/:name' => 'tags#xml', :as => 'tag_xml', :constraints => { name: /.+/ }
    get 'tag/:name/statistics' => 'tags#statistics', :as => 'tag_statistics', :constraints => { name: /.+/ }
    get 'tag/:name' => 'tags#show', :as => 'tag_show', :constraints => { name: /.+/ }, :defaults => { :format => 'html' }
    post 'tag/:name/description' => 'tags#description', :as => 'tag_description', :constraints => { name: /.+/ }

    get 'user/:username' => 'users#hub_items', :as => 'user_hub_items', :constraints => { username: /[^\/]+/ }
    get 'user/:username/tags' => 'tags#index', :as => 'user_hub_items_tags', :constraints => { username: /[^\/]+/ }
    get 'user/:username/filters' => 'tag_filters#index', :as => 'user_hub_items_filters', :constraints => { username: /[^\/]+/ }
    get 'user/:username/updates' => 'feed_retrievals#index', :as => 'user_hub_items_updates', :constraints => { username: /[^\/]+/ }
    get 'user/:username/about' => 'hub_feeds#show', :as => 'user_hub_items_about', :constraints => { username: /[^\/]+/ }

    get 'user/:username/rss' => 'users#tags_rss', :as => 'user_tags_rss', :constraints => { username: /[^\/]+/ }
    get 'user/:username/atom' => 'users#tags_atom', :as => 'user_tags_atom', :constraints => { username: /[^\/]+/ }
    get 'user/:username/json' => 'users#tags_json', :as => 'user_tags_json', :constraints => { username: /[^\/]+/ }
    get 'user/:username/xml' => 'users#tags_xml', :as => 'user_tags_xml', :constraints => { username: /[^\/]+/ }
    get 'user/:username/tag/:tagname(/:deprecated)' => 'users#tags', :as => 'user_tags_name', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/rss' => 'users#tags_rss', :as => 'user_tags_name_rss', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/atom' => 'users#tags_atom', :as => 'user_tags_name_atom', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/json' => 'users#tags_json', :as => 'user_tags_name_json', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }
    get 'user/:username/tag/:tagname(/:deprecated)/xml' => 'users#tags_xml', :as => 'user_tags_name_xml', :constraints => { tagname: /[^\/]+/, username: /.+/ }, defaults: { deprecated: nil }

    get 'tags_used_not_approved' => 'tags#tags_used_not_approved'
    get 'deprecated_tags' => 'tags#deprecated_tags'
    get 'tags_approved' => 'tags#tags_approved'

    member do
      get 'about'
      post 'recalc_all_tags'
      get 'item_search'
      post 'removed_tag_suggestion'
      post 'add_feed'
      put 'unsubscribe_feed/:feed_id' => 'hubs#unsubscribe_feed', as: 'unsubscribe_feed'
      get 'custom_republished_feeds'
      get 'tag_controls'
      get 'items'
      get 'by_date/:year/:month/:day' => 'hubs#by_date', :as => 'by_date'
      get 'retrievals'
      get 'my_bookmark_collections'
      get 'taggers'
      get 'team'
      get 'statistics'
      get 'notifications'
      get 'settings'
      get 'scoreboard'
      post 'add_roles'
      post 'remove_roles'
      post 'request_rights'
      get 'contact'
      get 'created'
      post 'set_notifications'
      post 'set_user_notifications'
      post 'set_settings'
      get 'active_taggers'
      post 'approve_tag'
      post 'unapprove_tag'
      post 'deprecate_tag'
      post 'undeprecate_tag'
      delete 'remove_delimiter'
      post 'leave'
    end

    collection do
      get 'list'
      get 'meta'
      get 'my'
      get 'background_activity'
      get 'all_items'
      get 'search'
      delete 'destroy_hubs', as: 'destroy_hubs'
    end

    resources :hub_feeds do
      collection do
        get 'autocomplete'
      end
      member do
        get 'reschedule_immediately'
        get 'more_details'
        get 'controls'
      end
    end

    resources :republished_feeds do
      member do
        get 'items'
        get 'inputs'
        get 'removals'
        get 'more_details'
      end
    end

    resources :tags do
      collection do
        get 'autocomplete'
      end
    end

    resources :tag_filters

    resources :feed_items do
      resources :tag_filters

      member do
        get 'tag_list'
        get 'content'
        get 'related'
        get 'tags_actions'
      end
      #      collection do
      #        get 'by_date/:year/:month/:day' => 'feed_items#by_date', :as => 'by_date'
      #      end
    end

    resources :messages, only: %i[new create]
  end

  devise_for :users, path: 'accounts', controllers: {
    registrations: 'users/registrations'
  }

  # Allow users to log out using both DELETE and GET
  devise_scope :user do
    get '/accounts/sign_out', to: 'devise/sessions#destroy'
  end

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.has_role? :superadmin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    root 'home#index'

    resources :user_approvals, only: [:index] do
      get :approve
      get :deny
    end

    resources :users, only: :index
    resources :hubs, only: %i[index destroy]
    resources :settings, only: %i[new create update]
  end
  root 'hubs#home'
end

app/helpers/tags_helper.rb
# frozen_string_literal: true
module TagsHelper
  def tag_cloud(tags, classes)
    # logger.info(tags.inspect)
    return [] if tags.empty?

    max_count = tags.sort_by(&:count).last.count.to_f

    tags.each do |tag|
      index = ((tag.count / max_count) * (classes.size - 1))
      yield tag, classes[index.nan? ? 0 : index.round]
    end
  end

  def tag_display(tag, options = {})
    options.merge!(:class => ['tag', options[:class]].compact.join(' '),
                   'data-tag-id' => tag.id,
                   'data-tag-name' => tag.name)

    hub_id = nil
    unless options[:hub].blank?
      options['data-hub-id'] = options[:hub].id
      hub_id = options[:hub].id
      options.delete(:hub)
    end

    unless options[:hub_feed].blank?
      options['data-hub-feed-id'] = options[:hub_feed].id
      options.delete(:hub_feed)
    end

    unless options[:hub_feed_item].blank?
      options['data-hub-feed-item-id'] = options[:hub_feed_item].id
      options.delete(:hub_feed_item)
    end

    unless options[:show_count].blank?
      tag_count = options[:use_count] ? tag.count : tag.count_by_hub(Hub.find(hub_id))
      options['data-tag-frequency'] = tag_count
      options.delete(:show_count)
    end

    if options[:allow_remove].present?
      if hub_filter_possible?(:add, params, current_user) || feed_filter_possible?(params, current_user) || item_filter_possible?(params, current_user)
        remove_tag_link = link_to_tag_filter(
          fa_icon('times', class: 'tag-remover'),
          'Delete',
          hub: @hub,
          item: @feed_item,
          tag: tag,
          tag_list: @feed_item.applied_tags(@hub).map(&:name),
          confirm: true,
          confirm_message: 'Are you sure to remove the "' + tag.name + '" tag?'
        )

        options.delete(:allow_remove)

        return link_to(
          tag.name,
          hub_tag_show_path(hub_id, tag.name),
          options
        ) + remove_tag_link
      end
    end

    link_to(tag.name, hub_tag_show_path(hub_id, tag.name), options)
  end

  def hub_filter_possible?(type, _params, current_user)
    roles = [:owner]

    case type
    when :add
      roles << :hub_tag_adder
    when :delete
      roles << :hub_tag_deleter
    when :modify
      roles << :hub_tag_modifier
    when :supplement
      roles << :hub_tag_supplementer
    end

    (current_user.is?(roles, @hub) || current_user.superadmin?) && !@already_filtered_for_hub
  end

  def feed_filter_possible?(params, current_user)
    params[:hub_feed_id].to_i != 0 &&
      (current_user.is?(%i[owner hub_feed_tag_filterer], @hub) || current_user.superadmin?) &&
      !@already_filtered_for_hub_feed
  end

  def item_filter_possible?(params, current_user)
    params[:hub_feed_item_id].to_i != 0 &&
      (current_user.is?(%i[owner hub_feed_item_tag_filterer], @hub) || current_user.superadmin?) &&
      !@already_filtered_for_hub_feed_item
  end

  def link_to_tag_filter(text, type, context = {})
    options = {
      class: 'add_filter_control',
      data_type: "#{type.to_s.capitalize}TagFilter"
    }

    if context[:tag]
      options[:data_id] = context[:tag].id
      options[:tag_name] = context[:tag].name
      options[:other_tags] = (context[:tag_list] - [context[:tag].name]).join(', ') if context[:tag_list]
    end
    options[:data_hub_id] = context[:hub].id
    options[:tag_list] = context[:tag_list].join(', ') if context[:tag_list]

    if context[:feed]
      path = hub_feed_tag_filters_path(context[:feed])
      add_class = 'hub_feed_tag_filter'
    elsif context[:hub] && context[:item]
      path = hub_feed_item_tag_filters_path(context[:hub], context[:item])
      add_class = 'hub_feed_item_tag_filter'
    elsif context[:hub]
      path = hub_tag_filters_path(context[:hub])
      add_class = 'hub_tag_filter'
    end

    if context[:confirm].present? && context[:confirm_message].present?
      options['data-confirm'] = context[:confirm_message]
    end

    options[:class] += ' ' + add_class

    link_to text, path, options
  end
end

app/views/tags/_graph_item.html.haml
%li
  = tag_display(tag, show_count: true, use_count: true, hub: hub, hub_feed: hub_feed)
  %span.tag-count
    = tag.count
  - if show_removed_tags
    = link_to '#', title: "#{@removed_tag_suggestions.include?(tag.id) ? 'Click to include this tag in' : 'Click to exclude this tag from'} the autocomplete tag list.", class: 'remove-suggestion-toggle', "data-hub-id": hub.id, "data-tag-id": tag.id do
      %span{ class: "fa #{@removed_tag_suggestions.include?(tag.id) ? 'fa-eye-slash' : 'fa-eye'}" }
  .tag-graph-bar{:style => "width: #{tag.count.to_f / max_count * 100}%"}

app/views/tags/_statistics.html.haml
- tags_count = tags.each.count
%h2 Statistics
%p
  There #{'is'.pluralize(tags_count)} currently
  %span.badge= tags_count
  = 'tag'.pluralize()
  in use in this hub.

- if prefixed_tags.any?
  = render partial: 'tag_statistics', locals: { tag_prefix: prefixed_tags.first[0], tag_count: prefixed_tags.first[1] }

  - if prefixed_tags.size > 1
    .panel-group#accordion{ role: 'tabllist', 'aria-multiselectable' => 'true' }
      .panel.panel-default
        .panel-heading#additional-tags-heading{ role: 'tab' }
          %h4.panel-title
            %a{ role: 'button', 'data-toggle' => 'collapse', 'data-parent' => '#accordion', href: '#additional-tags', 'aria-expanded' => 'true', 'aria-controls' => 'additional-tags' }
              Additional tag statistics
        .panel-collapse.collapse#additional-tags{ role: 'tabpanel', 'aria-labelledby' => 'additional-tags-heading' }
          .panel-body
            - prefixed_tags.drop(1).each do |tag_prefix, tag_count|
              = render partial: 'tag_statistics', locals: { tag_prefix: tag_prefix, tag_count: tag_count }

app/views/tags/_tabs.html.haml
%li{:class => "#{'active' if active == 'show' || active == 'show-grid'}"}
  = documentation('tagged-item-list')
  = link_to('Items', hub_tag_show_path(@hub, @tag.name))
  .nav-pill-arrow
- if current_user && current_user.is?([:owner, :stats_viewer], @hub)
  %li{:class => "#{'active' if active == 'statistics'}"}
    = documentation('tag-statistics')
    = link_to('Statistics', hub_tag_statistics_path(@hub, @tag.name))
    .nav-pill-arrow

app/views/tags/_tag_statistics.html.haml
%p
  There #{'is'.pluralize(tag_count)} currently
  %span.badge= tag_count
  = 'tag'.pluralize(tag_count)
  prefixed with
  %span.badge= tag_prefix + '.'
  in use in this hub.

app/views/tags/_top_panel.html.haml
.col-sm-8
  %h1
    Tag "
    %em>= tag
    " –
    \#{feed_items.count} #{'item'.pluralize(feed_items.count)}

  - if policy(hub).tag_descriptions?
    %p
      %span#readonly-tag-description{class: tag_description.nil? ? 'empty' : '' }
        #{tag_description.present? ? tag_description : 'Add a description'}
      = link_to '#', title: 'Edit this hub tag description', id: 'update-tag-description' do
        = fa_icon 'pencil'
      %textarea#tag-description.hidden.noEditor{placeholder: 'Add a description'}
        #{tag_description}
      = link_to hub_tag_description_url(hub, tag.name), title: 'Update this hub tag description', id: 'submit-tag-description', class: 'hidden' do
        = fa_icon 'check'
      = link_to '#', title: 'Cancel editing this hub tag description', id: 'cancel-tag-description', class: 'hidden' do
        = fa_icon 'close'
      - if @old_tag_description.present?
        %p.old-description
          An active hub-wide filter is changing tag <span class="tag">#{@tag_filter.tag.name}</span> to <span class="tag">#{@tag_filter.new_tag.name}</span>. The old tag, <span class="tag">#{@tag_filter.tag.name}</span>, had an accompanying definition. Would you like to move that definition to this page? #{link_to 'Yes', hub_tag_description_url(hub, tag.name), title: 'Apply this description.', id: 'apply-old-description', 'data-old-value': @old_tag_description.description}
  - elsif tag_description.present?
    %p
      %span#readonly-tag-description
        #{tag_description}


.col-sm-4
  .export-menu.text-right
    = link_to hub_tag_rss_path(hub, tag.name), title: 'An RSS feed of all items in this hub, with tag filters applied.', class: 'btn btn-default' do
      = image_tag('protocol_rss.png', width: 12, height: 12)
      RSS
      %span.badge
        = FeedSubscriber.count_for(hub_tag_rss_path(hub, tag.name))
    = link_to hub_tag_atom_path(hub, tag.name), title: 'An Atom feed of all items in this hub, with tag filters applied.', class: 'btn btn-default' do
      = image_tag('protocol_atom.png', width: 12, height: 12)
      ATOM
      %span.badge
        = FeedSubscriber.count_for(hub_tag_atom_path(hub, tag.name))
    = link_to hub_tag_json_path(hub, tag.name, callback: 'callback'), title: 'jsonp of all items in this hub, with tag filters applied.', class: 'btn btn-default' do
      = image_tag('protocol_json.png', width: 12, height: 12)
      JSON
      %span.badge
        = FeedSubscriber.count_for(hub_tag_json_path(hub, tag.name))

app/views/tags/deprecated_tags.html.haml
- content_for :top_panel do
  = render partial: 'hubs/top_panel', locals: { feed_items: @feed_items, hub: @hub, tag: @tag }
- content_for :tabs do
  = render partial: 'hubs/tabs', locals: { active: 'statistics' }
- content_for :tab_content do
  .nicely-padded.statistics
    %h1 Deprecated tags
    .row
      %form{ method: 'GET', action: hub_deprecated_tags_path(@hub) }
        %select#deprecated-tags-month{ name: 'month' }
          %option{ value: 'false', selected: @month == 'false' } All months
          - (Date::MONTHNAMES).each do |month|
            - unless month.nil?
              %option{ value: month, selected: @month == month }= month
        %select#deprecated-tags-year{ name: 'year' }
          %option{ value: 'false', selected: @year == 'false' } Select year
          - ( 2012..Time.current.year ).each do |year|
            %option{ value: year, selected: @year == year.to_s }= year
        %button
          Search
    .row
      - if @deprecated_hub_tags.any?
        %ul.list-unstyled#tag-cloud{ 'data-hub-id' => @hub.id }
          = render partial: 'tags/graph_item', as: :tag, collection: @deprecated_hub_tags,
            locals: { show_removed_tags: false, hub: @hub, hub_feed: nil, max_count: @deprecated_hub_tags.first.count }

app/views/tags/index.html.haml
- content_for :top_panel do
  = render partial: (@hub_feed ? 'hub_feeds' : 'hubs') + '/top_panel', locals: { hub: @hub, hub_feed: @hub_feed }
- content_for :tabs do
  - if @user
    = render partial: 'users/hub_items_tabs', locals: { active: 'tags' }
  - else
    = render partial: (@hub_feed ? 'hub_feeds' : 'hubs') + '/tabs', locals: { active: 'tags' }
- content_for :tab_content do
  .nicely-padded
    = render partial: 'statistics', locals: { tags: @tags, prefixed_tags: @prefixed_tags }
    %h2 Filter tags
    .form-group
      .row
        .col-xs-5
          .input-group
            %input.form-control#filter-by{ placeholder: 'Keyword', size: '15' }
            %span.input-group-btn
              %a.btn.btn-primary#filter-button{ href: '#' } Filter
        .col-sm-1
          %a#reset-filter{ href: '#' } Reset
    %h2 Sort tags
    .row
      .col-sm-3
        %select.form-control#sort-tags-by
          %option{ value: 'alpha' } Alphabetical
          %option{ selected: 'selected', value: 'frequency' } Frequency
      .col-sm-3
        %select.form-control#sort-tags-direction
          %option{ value: 'asc' } Ascending
          %option{ selected: 'selected', value: 'desc' } Descending

    %ul.list-unstyled#tag-cloud{ 'data-hub-id' => @hub.id }
      = render partial: 'tags/graph_item', as: :tag, collection: @tags,
        locals: { show_removed_tags: policy(@hub).removed_tag_suggestion?, hub: @hub, hub_feed: @hub_feed, max_count: @tags.empty? ? 0 : @tags.first.count }
    :javascript
      $(document).ready(
        function () {
          observeTagFilterControls()
          observeTagSortControls()
        }
      );

app/views/tags/show.html.haml
- content_for :title do
  = page_title(@tag.name)
- content_for :top_panel do
  = render partial: 'top_panel', locals: { feed_items: @feed_items, hub: @hub, tag: @tag, tag_description: @tag_description&.description, old_tag_description: @old_tag_description }
- content_for :tabs do
  = render partial: 'tabs', locals: { active: 'show' }
- content_for :tab_content do
  .hub-item-view.row
    .alter-views.col-md-12
      Sort by:
      - [{ key: 'Date tagged', default: 'desc' },{ key: 'Date published', default: 'desc' }].each do |option|
        \#{sortable_link(option[:key], params[:sort] || 'Date tagged', params.has_key?(:sort) && params[:sort] == option[:key] ? params[:order] : option[:default], 'hub_tag_show_path')} 
  = render partial: 'feed_items/alter_view', locals: { view: 'list', results: @feed_items }
  %ul.list-unstyled
    = render partial: 'feed_items/list_item', collection: @feed_items, as: :feed_item

app/views/tags/show_grid.html.haml
- content_for :top_panel do
  = render partial: 'top_panel', locals: { feed_items: @feed_items, hub: @hub, tag: @tag }
- content_for :tabs do
  = render partial: 'tabs', locals: { active: 'show-grid' }
- content_for :tab_content do
  .hub-item-view.row
    .alter-views.col-md-12
      Sort by:
      - [{ key: 'Date tagged', default: 'desc' },{ key: 'Date published', default: 'desc' }].each do |option|
        \#{sortable_link(option[:key], params[:sort] || 'Date tagged', params.has_key?(:sort) && params[:sort] == option[:key] ? params[:order] : option[:default], 'hub_tag_show_path', { view: 'grid' })} 
  = render partial: 'feed_items/alter_view', locals: { view: 'grid', results: @feed_items }
  %ul.list-unstyled
    = render partial: 'feed_items/grid', object: @feed_items, as: :feed_items

app/views/tags/statistics.html.haml
- content_for :top_panel do
  = render partial: 'top_panel', locals: { feed_items: @feed_items, hub: @hub, tag: @tag }
- content_for :tabs do
  = render partial: 'tabs', locals: { active: 'statistics' }
- content_for :tab_content do
  .nicely-padded
    %h1 Statistics
    %h2 Taggers
    - if @taggings_by_user.count == 0
      %p None
    - else
      %ul.list-unstyled
        - @taggings_by_user.each do |tagging_by_user|
          %li
            Tagged
            %a{ href: hub_user_tags_name_path(@hub, User.find(tagging_by_user['tagger_id']).username, @tag.name) }
              %span.badge= tagging_by_user['count']
            = 'time'.pluralize(tagging_by_user['count'])
            by
            %span.badge= User.find(tagging_by_user['tagger_id']).username
    - if @tag.deprecated?(@hub)
      %h2 Taggers before tag was deprecated
      %ul.list-unstyled
        - @before_deprecated_taggings_by_user.each do |tagging_by_user|
          %li
            Tagged
            %a{ href: hub_user_tags_name_path(@hub, User.find(tagging_by_user['tagger_id']).username, @tag.name, 'deprecated') }
              %span.badge= tagging_by_user['count']
            = 'time'.pluralize(tagging_by_user['count'])
            by
            %span.badge= User.find(tagging_by_user['tagger_id']).username
    - if @tag.deprecated?(@hub)
      %h2 Taggers after tag was deprecated
      %ul.list-unstyled
        - @after_deprecated_taggings_by_user.each do |tagging_by_user|
          %li
            Tagged
            %a{ href: hub_user_tags_name_path(@hub, User.find(tagging_by_user['tagger_id']).username, @tag.name, 'deprecated') }
              %span.badge= tagging_by_user['count']
            = 'time'.pluralize(tagging_by_user['count'])
            by
            %span.badge= User.find(tagging_by_user['tagger_id']).username

app/views/tags/tags_approved.html.haml
- content_for :top_panel do
  = render partial: 'hubs/top_panel', locals: { feed_items: @feed_items, hub: @hub, tag: @tag }
- content_for :tabs do
  = render partial: 'hubs/tabs', locals: { active: 'statistics' }
- content_for :tab_content do
  .nicely-padded.statistics
    %h1 Tags on the approved list
    .row
      - if @tags_approved.any?
        %ul.list-unstyled#tag-cloud{ 'data-hub-id' => @hub.id }
          = render partial: 'tags/graph_item', as: :tag, collection: @tags_approved,
            locals: { show_removed_tags: false, hub: @hub, hub_feed: nil, max_count: @tags_approved.first.count }

app/views/tags/tags_used_not_approved.html.haml
- content_for :top_panel do
  = render partial: 'hubs/top_panel', locals: { feed_items: @feed_items, hub: @hub, tag: @tag }
- content_for :tabs do
  = render partial: 'hubs/tabs', locals: { active: 'statistics' }
- content_for :tab_content do
  .nicely-padded.statistics
    %h1 Tags not listed on the approved tags list
    .row
      - if @hub.hub_approved_tags.any? && @tags_used_not_approved.any?
        %ul.list-unstyled#tag-cloud{ 'data-hub-id' => @hub.id }
          = render partial: 'tags/graph_item', as: :tag, collection: @tags_used_not_approved,
            locals: { show_removed_tags: false, hub: @hub, hub_feed: nil, max_count: @tags_used_not_approved.first.count }